apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: test
  labels:
    app: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: subedishiva61/python-fastapi:v1
        ports:
        - containerPort: 80