apiVersion: v1
kind: Service
metadata:
  name: fastapi-svc
  namespace: test
  labels:
    app: fastapi-projects
spec:
  type: NodePort
  selector:
    app: fastapi
  ports:
    - port: 80           # this can be change right here 
      targetPort: 8000   # it has match with program 